#############################################################
#
# Copyright 2015 F4E | European Joint Undertaking for ITER 
#  and the Development of Fusion Energy ('Fusion for Energy')
# 
# Licensed under the EUPL, Version 1.1 or - as soon they 
# will be approved by the European Commission - subsequent  
# versions of the EUPL (the "Licence"); 
# You may not use this work except in compliance with the 
# Licence. 
# You may obtain a copy of the Licence at: 
#  
# http://ec.europa.eu/idabc/eupl
#
# Unless required by applicable law or agreed to in 
# writing, software distributed under the Licence is 
# distributed on an "AS IS" basis, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either 
# express or implied. 
# See the Licence for the specific language governing 
# permissions and limitations under the Licence. 
#
#############################################################


include Makefile.inc
INCLUDES += -I$(MARTe2_DIR)/Lib/gtest-1.7.0/include
LIBRARIES   += ../../Build/$(TARGET)/Components/GAMs/GAMs$(LIBEXT)
LIBRARIES   += ../../Build/$(TARGET)/Components/DataSources/DataSources$(LIBEXT)
LIBRARIES   += ../../Build/$(TARGET)/Components/Interfaces/Interfaces$(LIBEXT)
LIBRARIES   += ../../Build/$(TARGET)/Components/Interfaces/InterfacesTest$(LIBEXT)

#LIBRARIES=$(BUILD_DIR)/Components/Interfaces/Interfaces$(LIBEXT)
#LIBRARIES=$(BUILD_DIR)/Components/Interfaces/InterfacesTest$(LIBEXT)

LIBRARIES   += -L$(MARTe2_DIR)/Build/$(TARGET)/Core/ -lMARTe2
LIBRARIES   += -L$(MARTe2_Components_DIR)/Build/$(TARGET)/Components/DataSources -lDataSources
LIBRARIES   += -L$(MARTe2_Components_DIR)/Build/$(TARGET)/Components/GAMs -lGAMs
LIBRARIES   += -L$(MARTe2_Components_DIR)/Build/$(TARGET)/Components/Interfaces -lInterfaces
LIBRARIES   += $(MARTe2_DIR)/Lib/gtest-1.7.0/libgtest.a $(MARTe2_DIR)/Lib/gtest-1.7.0/libgtest_main.a

ifdef MDSPLUS_DIR
LIBRARIES += -L$(MDSPLUS_DIR)/lib64 -L$(MDSPLUS_DIR)/lib -lMdsObjectsCppShr
endif


ifdef EPICS_BASE
LIBRARIES += -L$(EPICS_BASE)/lib/$(EPICS_HOST_ARCH)/ -lca -lCom -lcas -ldbCore -ldbRecStd -lgdd 
endif