# bin/bash
# BuildDiodeDB.sh
# Builds a Diode.db based on all .db files found in the directory

# Move to ExpandedDBs Dir


# Remove previous script outputs (clean build)
rm -rf Diode.db
rm -rf DiodeComplete.db
rm -rf DiodePVs.txt

echo "#File automatically generated by BuildDiodeDB.sh tool" >> Diode.db
echo "#All editing by hand will be removed when you run the tool again" >> Diode.db
echo " " >> Diode.db
less *.db >> Diode.db
less *.db >> DiodeComplete.db

# Remove fields 
declare -a REM_FIELDS=( "INP" "DTYP" "field(OUT,"
			"TMOD" "TMOT" "PORT" "ADDR" "OMAX" "IMAX" "IEOS" "OEOS" "IFMT" "OFMT"
			"LINR" "FLNK"
			"field(VAL,"
			"field(A," "field(B," "field(C," "field(D,"
			"SCAN" "ODLY"
			"SIMM" "SVAL"
			"NO_STATE" "NO_DEFECT"
			"field(PREC"
)


#sed -i.bak '/DTYP/d' ./Diode.db

for field in "${REM_FIELDS[@]}"
do 
	echo Removing "$field"
	sed -i "/$field/d" ./Diode.db
done

# Replace motor->ai

# Replace record(asyn->record(stringout

# record(listRecProfilSP2Acq -> record(longin

# and record(listRecProfilSP2Auto
# List of record names
more Diode.db | grep record | grep -o -P '(?<=\").*(?=\")' > DiodePVs.txt
sed -i -e 's/^/<si><t>/' DiodePVs.txt
sed -i -e 's/$/<\/t><\/si>/' DiodePVs.txt
# tr -d '\n' < DiodePVs.txt > DiodePVs.xml
awk '!a[$0]++' DiodePVs.txt > DiodePVs_uniq.txt
cp DiodePVs.txt DiodePVsALL.txt
cp  DiodePVs_uniq.txt DiodePVs.txt
wc -l DiodePVs*.txt

#Build one complete xml file to run in  one process
less Header.xml  > DiodePVs_One_Process.xml
tr -d '\n' < DiodePVs.txt >> DiodePVs_One_Process.xml
tr -d '\n' < DiodePVs_One_Process.xml > DiodePVs_One_Process_.xml
rm DiodePVs_One_Process.xml



# Build partial files for several processes
awk 'NR >= 1 && NR <= 10000'  DiodePVs.txt > DiodePVs_1.txt
awk 'NR >= 10001 && NR <= 20000'  DiodePVs.txt > DiodePVs_2.txt
awk 'NR >= 20001 && NR <= 30000'  DiodePVs.txt > DiodePVs_3.txt
awk 'NR >= 30001 && NR <= 40000'  DiodePVs.txt > DiodePVs_4.txt
echo '<si><t>MYFIRST:XML:PV</si></t>' > DiodePVs_5.txt
echo '<si><t>MYFIRST:XML:PV</si></t>' > DiodePVs_6.txt
echo '<si><t>MYFIRST:XML:PV</si></t>' > DiodePVs_7.txt
echo '<si><t>MYFIRST:XML:PV</si></t>' > DiodePVs_8.txt

#awk 'NR >= 28001 && NR <= 35000'  DiodePVs.txt > DiodePVs_5.txt
#awk 'NR >= 35001 && NR <= 42000'  DiodePVs.txt > DiodePVs_6.txt
#awk 'NR >= 42001 && NR <= 49000'  DiodePVs.txt > DiodePVs_7.txt
#awk 'NR >= 49001 && NR <= 56000'  DiodePVs.txt > DiodePVs_8.txt

less Header.xml  > DiodePVs_1.xml
tr -d '\n' < DiodePVs_1.txt >> DiodePVs_1.xml
tr -d '\n' < DiodePVs_1.xml > DiodePVs_1_.xml
rm DiodePVs_1.xml

less Header.xml  > DiodePVs_2.xml
tr -d '\n' < DiodePVs_2.txt >> DiodePVs_2.xml
tr -d '\n' < DiodePVs_2.xml > DiodePVs_2_.xml
rm DiodePVs_2.xml

less Header.xml  > DiodePVs_3.xml
tr -d '\n' < DiodePVs_3.txt >> DiodePVs_3.xml
tr -d '\n' < DiodePVs_3.xml > DiodePVs_3_.xml
rm DiodePVs_3.xml

less Header.xml  > DiodePVs_4.xml
tr -d '\n' < DiodePVs_4.txt >> DiodePVs_4.xml
tr -d '\n' < DiodePVs_4.xml > DiodePVs_4_.xml
rm DiodePVs_4.xml

less Header.xml  > DiodePVs_5.xml
tr -d '\n' < DiodePVs_5.txt >> DiodePVs_5.xml
tr -d '\n' < DiodePVs_5.xml > DiodePVs_5_.xml
rm DiodePVs_5.xml

less Header.xml  > DiodePVs_6.xml
tr -d '\n' < DiodePVs_6.txt >> DiodePVs_6.xml
tr -d '\n' < DiodePVs_6.xml > DiodePVs_6_.xml
rm DiodePVs_6.xml

less Header.xml  > DiodePVs_7.xml
tr -d '\n' < DiodePVs_7.txt >> DiodePVs_7.xml
tr -d '\n' < DiodePVs_7.xml > DiodePVs_7_.xml
rm DiodePVs_7.xml

less Header.xml  > DiodePVs_8.xml
tr -d '\n' < DiodePVs_8.txt >> DiodePVs_8.xml
tr -d '\n' < DiodePVs_8.xml > DiodePVs_8_.xml
rm DiodePVs_8.xml


